<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('countries')->insert(array ( 0 => array ( 'name' => 'Afghanistan', 'iso' => 'AFG', 'region' => 'Asia', 'isd_code' => '+93', 'currency' => 'AFN', 'symbol' => '؋', 'dollar_value' => 1),        
          1 => array ( 'name' => 'Aland Islands', 'iso' => 'ALA', 'region' => 'Europe', 'isd_code' => '+358', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          2 => array ( 'name' => 'Albania', 'iso' => 'ALB', 'region' => 'Europe', 'isd_code' => '+355', 'currency' => 'ALL', 'symbol' => 'L', 'dollar_value' => 1),        
          3 => array ( 'name' => 'Algeria', 'iso' => 'DZA', 'region' => 'Africa', 'isd_code' => '+213', 'currency' => 'DZD', 'symbol' => '$', 'dollar_value' => 1),        
          4 => array ( 'name' => 'American Samoa', 'iso' => 'ASM', 'region' => 'Oceania', 'isd_code' => '+1 684', 'currency' => 'USD', 'symbol' => '$', 'dollar_value' => 1),        
          5 => array ( 'name' => 'Andorra', 'iso' => 'AND', 'region' => 'Europe', 'isd_code' => '+376', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          6 => array ( 'name' => 'Angola', 'iso' => 'AGO', 'region' => 'Africa', 'isd_code' => '+244', 'currency' => 'AOA', 'symbol' => 'Kz', 'dollar_value' => 1),        
          7 => array ( 'name' => 'Anguilla', 'iso' => 'AIA', 'region' => 'Americas', 'isd_code' => '+1 264', 'currency' => 'XCD', 'symbol' => '$', 'dollar_value' => 1),        
          8 => array ( 'name' => 'Antarctica', 'iso' => 'ATA', 'region' => NULL, 'isd_code' => '+672', 'currency' => '', 'symbol' => '$', 'dollar_value' => 1),        
          9 => array ( 'name' => 'Antigua and Barbuda', 'iso' => 'ATG', 'region' => 'Americas', 'isd_code' => '+1 268', 'currency' => 'XCD', 'symbol' => '$', 'dollar_value' => 1),        
          10 => array ( 'name' => 'Argentina', 'iso' => 'ARG', 'region' => 'Americas', 'isd_code' => '+54', 'currency' => 'ARS', 'symbol' => 'AR$', 'dollar_value' => 1),        
          11 => array ( 'name' => 'Armenia', 'iso' => 'ARM', 'region' => 'Asia', 'isd_code' => '+374', 'currency' => 'AMD', 'symbol' => 'AMD', 'dollar_value' => 1),        
          12 => array ( 'name' => 'Aruba', 'iso' => 'ABW', 'region' => 'Americas', 'isd_code' => '+297', 'currency' => 'AWG', 'symbol' => 'Afl.', 'dollar_value' => 1),        
          13 => array ( 'name' => 'Australia', 'iso' => 'AUS', 'region' => 'Oceania', 'isd_code' => '+61', 'currency' => 'AUD', 'symbol' => 'AU$', 'dollar_value' => 1),        
          14 => array ( 'name' => 'Austria', 'iso' => 'AUT', 'region' => 'Europe', 'isd_code' => '+43', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          15 => array ( 'name' => 'Azerbaijan', 'iso' => 'AZE', 'region' => 'Asia', 'isd_code' => '+994', 'currency' => 'AZN', 'symbol' => 'man.', 'dollar_value' => 1),        
          16 => array ( 'name' => 'Bahamas', 'iso' => 'BHS', 'region' => 'Americas', 'isd_code' => '+1 242', 'currency' => 'BSD', 'symbol' => '$', 'dollar_value' => 1),        
          17 => array ( 'name' => 'Bahrain', 'iso' => 'BHR', 'region' => 'Asia', 'isd_code' => '+973', 'currency' => 'BHD', 'symbol' => '$', 'dollar_value' => 1),        
          18 => array ( 'name' => 'Bangladesh', 'iso' => 'BGD', 'region' => 'Asia', 'isd_code' => '+880', 'currency' => 'BDT', 'symbol' => '$', 'dollar_value' => 1),        
          19 => array ( 'name' => 'Barbados', 'iso' => 'BRB', 'region' => 'Americas', 'isd_code' => '+1 246', 'currency' => 'BBD', 'symbol' => '$', 'dollar_value' => 1),        
          20 => array ( 'name' => 'Belarus', 'iso' => 'BLR', 'region' => 'Europe', 'isd_code' => '+375', 'currency' => 'BYR', 'symbol' => '$', 'dollar_value' => 1),        
          21 => array ( 'name' => 'Belgium', 'iso' => 'BEL', 'region' => 'Europe', 'isd_code' => '+32', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          22 => array ( 'name' => 'Belize', 'iso' => 'BLZ', 'region' => 'Americas', 'isd_code' => '+501', 'currency' => 'BZD', 'symbol' => '$', 'dollar_value' => 1),        
          23 => array ( 'name' => 'Benin', 'iso' => 'BEN', 'region' => 'Africa', 'isd_code' => '+229', 'currency' => 'XOF', 'symbol' => '$', 'dollar_value' => 1),        
          24 => array ( 'name' => 'Bermuda', 'iso' => 'BMU', 'region' => 'Americas', 'isd_code' => '+1 441', 'currency' => 'BMD', 'symbol' => '$', 'dollar_value' => 1),        
          25 => array ( 'name' => 'Bhutan', 'iso' => 'BTN', 'region' => 'Asia', 'isd_code' => '+975', 'currency' => 'INR', 'symbol' => '$', 'dollar_value' => 1),        
          26 => array ( 'name' => 'Bolivia (Plurinational State of)', 'iso' => 'BOL', 'region' => 'Americas', 'isd_code' => '+591', 'currency' => 'BOB', 'symbol' => '$', 'dollar_value' => 1),        
          27 => array ( 'name' => 'Bonaire, Sint Eustatius and Saba', 'iso' => 'BES', 'region' => 'Americas', 'isd_code' => '+599', 'currency' => 'USD', 'symbol' => '$', 'dollar_value' => 1),        
          28 => array ( 'name' => 'Bosnia and Herzegovina', 'iso' => 'BIH', 'region' => 'Europe', 'isd_code' => '+387', 'currency' => 'BAM', 'symbol' => '$', 'dollar_value' => 1),        
          29 => array ( 'name' => 'Botswana', 'iso' => 'BWA', 'region' => 'Africa', 'isd_code' => '+267', 'currency' => 'BWP', 'symbol' => '$', 'dollar_value' => 1),        
          30 => array ( 'name' => 'Bouvet Island', 'iso' => 'BVT', 'region' => NULL, 'currency' => 'NOK', 'symbol' => '$', 'dollar_value' => 1, 'isd_code' => ''),        
          31 => array ( 'name' => 'Brazil', 'iso' => 'BRA', 'region' => 'Americas', 'isd_code' => '+55', 'currency' => 'BRL', 'symbol' => '$', 'dollar_value' => 1),        
          32 => array ( 'name' => 'British Indian Ocean Territory', 'iso' => 'IOT', 'region' => NULL, 'isd_code' => '+246', 'currency' => 'USD', 'symbol' => '$', 'dollar_value' => 1),        
          33 => array ( 'name' => 'Brunei Darussalam', 'iso' => 'BRN', 'region' => 'Asia', 'isd_code' => '+673', 'currency' => 'BND', 'symbol' => '$', 'dollar_value' => 1),        
          34 => array ( 'name' => 'Bulgaria', 'iso' => 'BGR', 'region' => 'Europe', 'isd_code' => '+359', 'currency' => 'BGN', 'symbol' => '$', 'dollar_value' => 1),        
          35 => array ( 'name' => 'Burkina Faso', 'iso' => 'BFA', 'region' => 'Africa', 'isd_code' => '+226', 'currency' => 'XOF', 'symbol' => '$', 'dollar_value' => 1),        
          36 => array ( 'name' => 'Burundi', 'iso' => 'BDI', 'region' => 'Africa', 'isd_code' => '+257', 'currency' => 'BIF', 'symbol' => '$', 'dollar_value' => 1),        
          37 => array ( 'name' => 'Cambodia', 'iso' => 'KHM', 'region' => 'Asia', 'isd_code' => '+855', 'currency' => 'KHR', 'symbol' => '$', 'dollar_value' => 1),        
          38 => array ( 'name' => 'Cameroon', 'iso' => 'CMR', 'region' => 'Africa', 'isd_code' => '+237', 'currency' => 'XAF', 'symbol' => '$', 'dollar_value' => 1),        
          39 => array ( 'name' => 'Canada', 'iso' => 'CAN', 'region' => 'Americas', 'isd_code' => '+1', 'currency' => 'CAD', 'symbol' => 'CA$', 'dollar_value' => 1),        
          40 => array ( 'name' => 'Cabo Verde', 'iso' => 'CPV', 'region' => 'Africa', 'isd_code' => '+238', 'currency' => 'CVE', 'symbol' => '$', 'dollar_value' => 1),        
          41 => array ( 'name' => 'Cayman Islands', 'iso' => 'CYM', 'region' => 'Americas', 'isd_code' => '+1 345', 'currency' => 'KYD', 'symbol' => '$', 'dollar_value' => 1),        
          42 => array ( 'name' => 'Central African Republic', 'iso' => 'CAF', 'region' => 'Africa', 'isd_code' => '+236', 'currency' => 'XAF', 'symbol' => '$', 'dollar_value' => 1),        
          43 => array ( 'name' => 'Chad', 'iso' => 'TCD', 'region' => 'Africa', 'isd_code' => '+235', 'currency' => 'XAF', 'symbol' => '$', 'dollar_value' => 1),        
          44 => array ( 'name' => 'Chile', 'iso' => 'CHL', 'region' => 'Americas', 'isd_code' => '+56', 'currency' => 'CLP', 'symbol' => '$', 'dollar_value' => 1),        
          45 => array ( 'name' => 'China', 'iso' => 'CHN', 'region' => 'Asia', 'isd_code' => '+86', 'currency' => 'CNY', 'symbol' => '$', 'dollar_value' => 1),        
          46 => array ( 'name' => 'Christmas Island', 'iso' => 'CXR', 'region' => NULL, 'isd_code' => '+61', 'currency' => 'AUD', 'symbol' => 'AU$', 'dollar_value' => 1),        
          47 => array ( 'name' => 'Cocos (Keeling) Islands', 'iso' => 'CCK', 'region' => NULL, 'isd_code' => '+61', 'currency' => 'AUD', 'symbol' => 'AU$', 'dollar_value' => 1),        
          48 => array ( 'name' => 'Colombia', 'iso' => 'COL', 'region' => 'Americas', 'isd_code' => '+57', 'currency' => 'COP', 'symbol' => '$', 'dollar_value' => 1),        
          49 => array ( 'name' => 'Comoros', 'iso' => 'COM', 'region' => 'Africa', 'isd_code' => '+269', 'currency' => 'KMF', 'symbol' => '$', 'dollar_value' => 1),        
          50 => array ( 'name' => 'Congo', 'iso' => 'COG', 'region' => 'Africa', 'isd_code' => '+242', 'currency' => 'XAF', 'symbol' => '$', 'dollar_value' => 1),        
          51 => array ( 'name' => 'Congo (Democratic Republic of the)', 'iso' => 'COD', 'region' => 'Africa', 'isd_code' => '+243', 'currency' => 'CDF', 'symbol' => '$', 'dollar_value' => 1),        
          52 => array ( 'name' => 'Cook Islands', 'iso' => 'COK', 'region' => 'Oceania', 'isd_code' => '+682', 'currency' => 'NZD', 'symbol' => '$', 'dollar_value' => 1),        
          53 => array ( 'name' => 'Costa Rica', 'iso' => 'CRI', 'region' => 'Americas', 'isd_code' => '+506', 'currency' => 'CRC', 'symbol' => '$', 'dollar_value' => 1),        
          54 => array ( 'name' => 'Côte d\'Ivoire', 'iso' => 'CIV', 'region' => 'Africa', 'isd_code' => '+225', 'currency' => 'XOF', 'symbol' => '$', 'dollar_value' => 1),        
          55 => array ( 'name' => 'Croatia', 'iso' => 'HRV', 'region' => 'Europe', 'isd_code' => '+385', 'currency' => 'HRK', 'symbol' => '$', 'dollar_value' => 1),        
          56 => array ( 'name' => 'Cuba', 'iso' => 'CUB', 'region' => 'Americas', 'isd_code' => '+53', 'currency' => 'CUP', 'symbol' => '$', 'dollar_value' => 1),        
          57 => array ( 'name' => 'Curaçao', 'iso' => 'CUW', 'region' => 'Americas', 'isd_code' => '+599', 'currency' => 'ANG', 'symbol' => 'NAƒ', 'dollar_value' => 1),        
          58 => array ( 'name' => 'Cyprus', 'iso' => 'CYP', 'region' => 'Asia', 'isd_code' => '+357', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          59 => array ( 'name' => 'Czech Republic', 'iso' => 'CZE', 'region' => 'Europe', 'isd_code' => '+420', 'currency' => 'CZK', 'symbol' => '$', 'dollar_value' => 1),        
          60 => array ( 'name' => 'Denmark', 'iso' => 'DNK', 'region' => 'Europe', 'isd_code' => '+45', 'currency' => 'DKK', 'symbol' => 'kr', 'dollar_value' => 1),        
          61 => array ( 'name' => 'Djibouti', 'iso' => 'DJI', 'region' => 'Africa', 'isd_code' => '+253', 'currency' => 'DJF', 'symbol' => '$', 'dollar_value' => 1),        
          62 => array ( 'name' => 'Dominica', 'iso' => 'DMA', 'region' => 'Americas', 'isd_code' => '+1 767', 'currency' => 'XCD', 'symbol' => '$', 'dollar_value' => 1),        
          63 => array ( 'name' => 'Dominican Republic', 'iso' => 'DOM', 'region' => 'Americas', 'isd_code' => '+1 809', 'currency' => 'DOP', 'symbol' => '$', 'dollar_value' => 1),        
          64 => array ( 'name' => 'Ecuador', 'iso' => 'ECU', 'region' => 'Americas', 'isd_code' => '+593', 'currency' => 'USD', 'symbol' => '$', 'dollar_value' => 1),        
          65 => array ( 'name' => 'Egypt', 'iso' => 'EGY', 'region' => 'Africa', 'isd_code' => '+20', 'currency' => 'EGP', 'symbol' => '$', 'dollar_value' => 1),        
          66 => array ( 'name' => 'El Salvador', 'iso' => 'SLV', 'region' => 'Americas', 'isd_code' => '+503', 'currency' => 'USD', 'symbol' => '$', 'dollar_value' => 1),        
          67 => array ( 'name' => 'Equatorial Guinea', 'iso' => 'GNQ', 'region' => 'Africa', 'isd_code' => '+240', 'currency' => 'XAF', 'symbol' => '$', 'dollar_value' => 1),        
          68 => array ( 'name' => 'Eritrea', 'iso' => 'ERI', 'region' => 'Africa', 'isd_code' => '+291', 'currency' => 'ERN', 'symbol' => '$', 'dollar_value' => 1),        
          69 => array ( 'name' => 'Estonia', 'iso' => 'EST', 'region' => 'Europe', 'isd_code' => '+372', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          70 => array ( 'name' => 'Ethiopia', 'iso' => 'ETH', 'region' => 'Africa', 'isd_code' => '+251', 'currency' => 'ETB', 'symbol' => '$', 'dollar_value' => 1),        
          71 => array ( 'name' => 'Falkland Islands (Malvinas)', 'iso' => 'FLK', 'region' => 'Americas', 'isd_code' => '+500', 'currency' => 'FKP', 'symbol' => '$', 'dollar_value' => 1),        
          72 => array ( 'name' => 'Faroe Islands', 'iso' => 'FRO', 'region' => 'Europe', 'isd_code' => '+298', 'currency' => 'DKK', 'symbol' => 'kr', 'dollar_value' => 1),        
          73 => array ( 'name' => 'Fiji', 'iso' => 'FJI', 'region' => 'Oceania', 'isd_code' => '+679', 'currency' => 'FJD', 'symbol' => '$', 'dollar_value' => 1),        
          74 => array ( 'name' => 'Finland', 'iso' => 'FIN', 'region' => 'Europe', 'isd_code' => '+358', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          75 => array ( 'name' => 'France', 'iso' => 'FRA', 'region' => 'Europe', 'isd_code' => '+33', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          76 => array ( 'name' => 'French Guiana', 'iso' => 'GUF', 'region' => 'Americas', 'isd_code' => '+594', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          77 => array ( 'name' => 'French Polynesia', 'iso' => 'PYF', 'region' => 'Oceania', 'isd_code' => '+689', 'currency' => 'XPF', 'symbol' => '$', 'dollar_value' => 1),        
          78 => array ( 'name' => 'French Southern Territories', 'iso' => 'ATF', 'region' => NULL, 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1, 'isd_code' => ''),        
          79 => array ( 'name' => 'Gabon', 'iso' => 'GAB', 'region' => 'Africa', 'isd_code' => '+241', 'currency' => 'XAF', 'symbol' => '$', 'dollar_value' => 1),        
          80 => array ( 'name' => 'Gambia', 'iso' => 'GMB', 'region' => 'Africa', 'isd_code' => '+220', 'currency' => 'GMD', 'symbol' => '$', 'dollar_value' => 1),        
          81 => array ( 'name' => 'Georgia', 'iso' => 'GEO', 'region' => 'Asia', 'isd_code' => '+995', 'currency' => 'GEL', 'symbol' => '$', 'dollar_value' => 1),        
          82 => array ( 'name' => 'Germany', 'iso' => 'DEU', 'region' => 'Europe', 'isd_code' => '+49', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          83 => array ( 'name' => 'Ghana', 'iso' => 'GHA', 'region' => 'Africa', 'isd_code' => '+233', 'currency' => 'GHS', 'symbol' => '$', 'dollar_value' => 1),        
          84 => array ( 'name' => 'Gibraltar', 'iso' => 'GIB', 'region' => 'Europe', 'isd_code' => '+350', 'currency' => 'GIP', 'symbol' => '$', 'dollar_value' => 1),        
          85 => array ( 'name' => 'Greece', 'iso' => 'GRC', 'region' => 'Europe', 'isd_code' => '+30', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          86 => array ( 'name' => 'Greenland', 'iso' => 'GRL', 'region' => 'Americas', 'isd_code' => '+299', 'currency' => 'DKK', 'symbol' => 'kr', 'dollar_value' => 1),        
          87 => array ( 'name' => 'Grenada', 'iso' => 'GRD', 'region' => 'Americas', 'isd_code' => '+473', 'currency' => 'XCD', 'symbol' => '$', 'dollar_value' => 1),        
          88 => array ( 'name' => 'Guadeloupe', 'iso' => 'GLP', 'region' => 'Americas', 'isd_code' => '+590', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          89 => array ( 'name' => 'Guam', 'iso' => 'GUM', 'region' => 'Oceania', 'isd_code' => '+1 671', 'currency' => 'USD', 'symbol' => '$', 'dollar_value' => 1),        
          90 => array ( 'name' => 'Guatemala', 'iso' => 'GTM', 'region' => 'Americas', 'isd_code' => '+502', 'currency' => 'GTQ', 'symbol' => '$', 'dollar_value' => 1),        
          91 => array ( 'name' => 'Guernsey', 'iso' => 'GGY', 'region' => 'Europe', 'isd_code' => '+44', 'currency' => 'GBP', 'symbol' => '£', 'dollar_value' => 1),        
          92 => array ( 'name' => 'Guinea', 'iso' => 'GIN', 'region' => 'Africa', 'isd_code' => '+224', 'currency' => 'GNF', 'symbol' => '$', 'dollar_value' => 1),        
          93 => array ( 'name' => 'Guinea-Bissau', 'iso' => 'GNB', 'region' => 'Africa', 'isd_code' => '+245', 'currency' => 'XOF', 'symbol' => '$', 'dollar_value' => 1),        
          94 => array ( 'name' => 'Guyana', 'iso' => 'GUY', 'region' => 'Americas', 'isd_code' => '+592', 'currency' => 'GYD', 'symbol' => '$', 'dollar_value' => 1),        
          95 => array ( 'name' => 'Haiti', 'iso' => 'HTI', 'region' => 'Americas', 'isd_code' => '+509', 'currency' => 'HTG', 'symbol' => '$', 'dollar_value' => 1),        
          96 => array ( 'name' => 'Heard Island and McDonald Islands', 'iso' => 'HMD', 'region' => NULL, 'currency' => 'AUD', 'symbol' => 'AU$', 'dollar_value' => 1, 'isd_code' => ''),        
          97 => array ( 'name' => 'Holy See', 'iso' => 'VAT', 'region' => 'Europe', 'isd_code' => '+379', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          98 => array ( 'name' => 'Honduras', 'iso' => 'HND', 'region' => 'Americas', 'isd_code' => '+504', 'currency' => 'HNL', 'symbol' => '$', 'dollar_value' => 1),        
          99 => array ( 'name' => 'Hong Kong', 'iso' => 'HKG', 'region' => 'Asia', 'isd_code' => '+852', 'currency' => 'HKD', 'symbol' => '$', 'dollar_value' => 1),        
          100 => array ( 'name' => 'Hungary', 'iso' => 'HUN', 'region' => 'Europe', 'isd_code' => '+36', 'currency' => 'HUF', 'symbol' => '$', 'dollar_value' => 1),        
          101 => array ( 'name' => 'Iceland', 'iso' => 'ISL', 'region' => 'Europe', 'isd_code' => '+354', 'currency' => 'ISK', 'symbol' => '$', 'dollar_value' => 1),        
          102 => array ( 'name' => 'India', 'iso' => 'IND', 'region' => 'Asia', 'isd_code' => '+91', 'currency' => 'INR', 'symbol' => '$', 'dollar_value' => 1),        
          103 => array ( 'name' => 'Indonesia', 'iso' => 'IDN', 'region' => 'Asia', 'isd_code' => '+62', 'currency' => 'IDR', 'symbol' => '$', 'dollar_value' => 1),        
          104 => array ( 'name' => 'Iran (Islamic Republic of)', 'iso' => 'IRN', 'region' => 'Asia', 'isd_code' => '+98', 'currency' => 'IRR', 'symbol' => '$', 'dollar_value' => 1),        
          105 => array ( 'name' => 'Iraq', 'iso' => 'IRQ', 'region' => 'Asia', 'isd_code' => '+964', 'currency' => 'IQD', 'symbol' => '$', 'dollar_value' => 1),        
          106 => array ( 'name' => 'Ireland', 'iso' => 'IRL', 'region' => 'Europe', 'isd_code' => '+353', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          107 => array ( 'name' => 'Isle of Man', 'iso' => 'IMN', 'region' => 'Europe', 'isd_code' => '+44', 'currency' => 'GBP', 'symbol' => '£', 'dollar_value' => 1),        
          108 => array ( 'name' => 'Israel', 'iso' => 'ISR', 'region' => 'Asia', 'isd_code' => '+972', 'currency' => 'ILS', 'symbol' => '$', 'dollar_value' => 1),        
          109 => array ( 'name' => 'Italy', 'iso' => 'ITA', 'region' => 'Europe', 'isd_code' => '+39', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          110 => array ( 'name' => 'Jamaica', 'iso' => 'JAM', 'region' => 'Americas', 'isd_code' => '+1 876', 'currency' => 'JMD', 'symbol' => '$', 'dollar_value' => 1),        
          111 => array ( 'name' => 'Japan', 'iso' => 'JPN', 'region' => 'Asia', 'isd_code' => '+81', 'currency' => 'JPY', 'symbol' => '¥', 'dollar_value' => 1),        
          112 => array ( 'name' => 'Jersey', 'iso' => 'JEY', 'region' => 'Europe', 'isd_code' => '+44', 'currency' => 'GBP', 'symbol' => '£', 'dollar_value' => 1),        
          113 => array ( 'name' => 'Jordan', 'iso' => 'JOR', 'region' => 'Asia', 'isd_code' => '+962', 'currency' => 'JOD', 'symbol' => '$', 'dollar_value' => 1),        
          114 => array ( 'name' => 'Kazakhstan', 'iso' => 'KAZ', 'region' => 'Asia', 'isd_code' => '+7', 'currency' => 'KZT', 'symbol' => '$', 'dollar_value' => 1),        
          115 => array ( 'name' => 'Kenya', 'iso' => 'KEN', 'region' => 'Africa', 'isd_code' => '+254', 'currency' => 'KES', 'symbol' => '$', 'dollar_value' => 1),        
          116 => array ( 'name' => 'Kiribati', 'iso' => 'KIR', 'region' => 'Oceania', 'isd_code' => '+686', 'currency' => 'AUD', 'symbol' => 'AU$', 'dollar_value' => 1),        
          117 => array ( 'name' => 'Korea (Democratic People\'s Republic of)', 'iso' => 'PRK', 'region' => 'Asia', 'isd_code' => '+850', 'currency' => 'KPW', 'symbol' => '$', 'dollar_value' => 1),        
          118 => array ( 'name' => 'Korea (Republic of)', 'iso' => 'KOR', 'region' => 'Asia', 'isd_code' => '+82', 'currency' => 'KRW', 'symbol' => '$', 'dollar_value' => 1),        
          119 => array ( 'name' => 'Kuwait', 'iso' => 'KWT', 'region' => 'Asia', 'isd_code' => '+965', 'currency' => 'KWD', 'symbol' => '$', 'dollar_value' => 1),        
          120 => array ( 'name' => 'Kyrgyzstan', 'iso' => 'KGZ', 'region' => 'Asia', 'isd_code' => '+996', 'currency' => 'KGS', 'symbol' => '$', 'dollar_value' => 1),        
          121 => array ( 'name' => 'Lao People\'s Democratic Republic', 'iso' => 'LAO', 'region' => 'Asia', 'isd_code' => '+856', 'currency' => 'LAK', 'symbol' => '$', 'dollar_value' => 1),        
          122 => array ( 'name' => 'Latvia', 'iso' => 'LVA', 'region' => 'Europe', 'isd_code' => '+371', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          123 => array ( 'name' => 'Lebanon', 'iso' => 'LBN', 'region' => 'Asia', 'isd_code' => '+961', 'currency' => 'LBP', 'symbol' => '$', 'dollar_value' => 1),        
          124 => array ( 'name' => 'Lesotho', 'iso' => 'LSO', 'region' => 'Africa', 'isd_code' => '+266', 'currency' => 'LSL', 'symbol' => '$', 'dollar_value' => 1),        
          125 => array ( 'name' => 'Liberia', 'iso' => 'LBR', 'region' => 'Africa', 'isd_code' => '+231', 'currency' => 'LRD', 'symbol' => '$', 'dollar_value' => 1),        
          126 => array ( 'name' => 'Libya', 'iso' => 'LBY', 'region' => 'Africa', 'isd_code' => '+218', 'currency' => 'LYD', 'symbol' => '$', 'dollar_value' => 1),        
          127 => array ( 'name' => 'Liechtenstein', 'iso' => 'LIE', 'region' => 'Europe', 'isd_code' => '+423', 'currency' => 'CHF', 'symbol' => '$', 'dollar_value' => 1),        
          128 => array ( 'name' => 'Lithuania', 'iso' => 'LTU', 'region' => 'Europe', 'isd_code' => '+370', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          129 => array ( 'name' => 'Luxembourg', 'iso' => 'LUX', 'region' => 'Europe', 'isd_code' => '+352', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          130 => array ( 'name' => 'Macao', 'iso' => 'MAC', 'region' => 'Asia', 'isd_code' => '+853', 'currency' => 'MOP', 'symbol' => '$', 'dollar_value' => 1),        
          131 => array ( 'name' => 'Macedonia (the former Yugoslav Republic of)', 'iso' => 'MKD', 'region' => 'Europe', 'isd_code' => '+389', 'currency' => 'MKD', 'symbol' => '$', 'dollar_value' => 1),        
          132 => array ( 'name' => 'Madagascar', 'iso' => 'MDG', 'region' => 'Africa', 'isd_code' => '+261', 'currency' => 'MGA', 'symbol' => '$', 'dollar_value' => 1),        
          133 => array ( 'name' => 'Malawi', 'iso' => 'MWI', 'region' => 'Africa', 'isd_code' => '+265', 'currency' => 'MWK', 'symbol' => '$', 'dollar_value' => 1),        
          134 => array ( 'name' => 'Malaysia', 'iso' => 'MYS', 'region' => 'Asia', 'isd_code' => '+60', 'currency' => 'MYR', 'symbol' => '$', 'dollar_value' => 1),        
          135 => array ( 'name' => 'Maldives', 'iso' => 'MDV', 'region' => 'Asia', 'isd_code' => '+960', 'currency' => 'MVR', 'symbol' => '$', 'dollar_value' => 1),        
          136 => array ( 'name' => 'Mali', 'iso' => 'MLI', 'region' => 'Africa', 'isd_code' => '+223', 'currency' => 'XOF', 'symbol' => '$', 'dollar_value' => 1),        
          137 => array ( 'name' => 'Malta', 'iso' => 'MLT', 'region' => 'Europe', 'isd_code' => '+356', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          138 => array ( 'name' => 'Marshall Islands', 'iso' => 'MHL', 'region' => 'Oceania', 'isd_code' => '+692', 'currency' => 'USD', 'symbol' => '$', 'dollar_value' => 1),        
          139 => array ( 'name' => 'Martinique', 'iso' => 'MTQ', 'region' => 'Americas', 'isd_code' => '+596', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          140 => array ( 'name' => 'Mauritania', 'iso' => 'MRT', 'region' => 'Africa', 'isd_code' => '+222', 'currency' => 'MRO', 'symbol' => '$', 'dollar_value' => 1),        
          141 => array ( 'name' => 'Mauritius', 'iso' => 'MUS', 'region' => 'Africa', 'isd_code' => '+230', 'currency' => 'MUR', 'symbol' => '$', 'dollar_value' => 1),        
          142 => array ( 'name' => 'Mayotte', 'iso' => 'MYT', 'region' => 'Africa', 'isd_code' => '+262', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          143 => array ( 'name' => 'Mexico', 'iso' => 'MEX', 'region' => 'Americas', 'isd_code' => '+52', 'currency' => 'MXN', 'symbol' => '$', 'dollar_value' => 1),        
          144 => array ( 'name' => 'Micronesia (Federated States of)', 'iso' => 'FSM', 'region' => 'Oceania', 'isd_code' => '+691', 'currency' => 'USD', 'symbol' => '$', 'dollar_value' => 1),        
          145 => array ( 'name' => 'Moldova (Republic of)', 'iso' => 'MDA', 'region' => 'Europe', 'isd_code' => '+373', 'currency' => 'MDL', 'symbol' => '$', 'dollar_value' => 1),        
          146 => array ( 'name' => 'Monaco', 'iso' => 'MCO', 'region' => 'Europe', 'isd_code' => '+377', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          147 => array ( 'name' => 'Mongolia', 'iso' => 'MNG', 'region' => 'Asia', 'isd_code' => '+976', 'currency' => 'MNT', 'symbol' => '$', 'dollar_value' => 1),        
          148 => array ( 'name' => 'Montenegro', 'iso' => 'MNE', 'region' => 'Europe', 'isd_code' => '+382', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          149 => array ( 'name' => 'Montserrat', 'iso' => 'MSR', 'region' => 'Americas', 'isd_code' => '+1 664', 'currency' => 'XCD', 'symbol' => '$', 'dollar_value' => 1),        
          150 => array ( 'name' => 'Morocco', 'iso' => 'MAR', 'region' => 'Africa', 'isd_code' => '+212', 'currency' => 'MAD', 'symbol' => '$', 'dollar_value' => 1),        
          151 => array ( 'name' => 'Mozambique', 'iso' => 'MOZ', 'region' => 'Africa', 'isd_code' => '+258', 'currency' => 'MZN', 'symbol' => '$', 'dollar_value' => 1),        
          152 => array ( 'name' => 'Myanmar', 'iso' => 'MMR', 'region' => 'Asia', 'isd_code' => '+95', 'currency' => 'MMK', 'symbol' => '$', 'dollar_value' => 1),        
          153 => array ( 'name' => 'Namibia', 'iso' => 'NAM', 'region' => 'Africa', 'isd_code' => '+264', 'currency' => 'NAD', 'symbol' => '$', 'dollar_value' => 1),        
          154 => array ( 'name' => 'Nauru', 'iso' => 'NRU', 'region' => 'Oceania', 'isd_code' => '+674', 'currency' => 'AUD', 'symbol' => 'AU$', 'dollar_value' => 1),        
          155 => array ( 'name' => 'Nepal', 'iso' => 'NPL', 'region' => 'Asia', 'isd_code' => '+977', 'currency' => 'NPR', 'symbol' => '$', 'dollar_value' => 1),        
          156 => array ( 'name' => 'Netherlands', 'iso' => 'NLD', 'region' => 'Europe', 'isd_code' => '+31', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          157 => array ( 'name' => 'New Caledonia', 'iso' => 'NCL', 'region' => 'Oceania', 'isd_code' => '+687', 'currency' => 'XPF', 'symbol' => '$', 'dollar_value' => 1),        
          158 => array ( 'name' => 'New Zealand', 'iso' => 'NZL', 'region' => 'Oceania', 'isd_code' => '+64', 'currency' => 'NZD', 'symbol' => '$', 'dollar_value' => 1),        
          159 => array ( 'name' => 'Nicaragua', 'iso' => 'NIC', 'region' => 'Americas', 'isd_code' => '+505', 'currency' => 'NIO', 'symbol' => '$', 'dollar_value' => 1),        
          160 => array ( 'name' => 'Niger', 'iso' => 'NER', 'region' => 'Africa', 'isd_code' => '+227', 'currency' => 'XOF', 'symbol' => '$', 'dollar_value' => 1),        
          161 => array ( 'name' => 'Nigeria', 'iso' => 'NGA', 'region' => 'Africa', 'isd_code' => '+234', 'currency' => 'NGN', 'symbol' => '$', 'dollar_value' => 1),        
          162 => array ( 'name' => 'Niue', 'iso' => 'NIU', 'region' => 'Oceania', 'isd_code' => '+683', 'currency' => 'NZD', 'symbol' => '$', 'dollar_value' => 1),        
          163 => array ( 'name' => 'Norfolk Island', 'iso' => 'NFK', 'region' => 'Oceania', 'isd_code' => '+672', 'currency' => 'AUD', 'symbol' => 'AU$', 'dollar_value' => 1),        
          164 => array ( 'name' => 'Northern Mariana Islands', 'iso' => 'MNP', 'region' => 'Oceania', 'isd_code' => '+1 670', 'currency' => 'USD', 'symbol' => '$', 'dollar_value' => 1),        
          165 => array ( 'name' => 'Norway', 'iso' => 'NOR', 'region' => 'Europe', 'isd_code' => '+47', 'currency' => 'NOK', 'symbol' => '$', 'dollar_value' => 1),        
          166 => array ( 'name' => 'Oman', 'iso' => 'OMN', 'region' => 'Asia', 'isd_code' => '+968', 'currency' => 'OMR', 'symbol' => '$', 'dollar_value' => 1),        
          167 => array ( 'name' => 'Pakistan', 'iso' => 'PAK', 'region' => 'Asia', 'isd_code' => '+92', 'currency' => 'PKR', 'symbol' => '$', 'dollar_value' => 1),        
          168 => array ( 'name' => 'Palau', 'iso' => 'PLW', 'region' => 'Oceania', 'isd_code' => '+680', 'currency' => 'USD', 'symbol' => '$', 'dollar_value' => 1),        
          169 => array ( 'name' => 'Palestine, State of', 'iso' => 'PSE', 'region' => 'Asia', 'isd_code' => '+970', 'currency' => 'JOD', 'symbol' => '$', 'dollar_value' => 1),        
          170 => array ( 'name' => 'Panama', 'iso' => 'PAN', 'region' => 'Americas', 'isd_code' => '+507', 'currency' => 'PAB', 'symbol' => '$', 'dollar_value' => 1),        
          171 => array ( 'name' => 'Papua New Guinea', 'iso' => 'PNG', 'region' => 'Oceania', 'isd_code' => '+675', 'currency' => 'PGK', 'symbol' => '$', 'dollar_value' => 1),        
          172 => array ( 'name' => 'Paraguay', 'iso' => 'PRY', 'region' => 'Americas', 'isd_code' => '+595', 'currency' => 'PYG', 'symbol' => '$', 'dollar_value' => 1),        
          173 => array ( 'name' => 'Peru', 'iso' => 'PER', 'region' => 'Americas', 'isd_code' => '+51', 'currency' => 'PEN', 'symbol' => '$', 'dollar_value' => 1),        
          174 => array ( 'name' => 'Philippines', 'iso' => 'PHL', 'region' => 'Asia', 'isd_code' => '+63', 'currency' => 'PHP', 'symbol' => '$', 'dollar_value' => 1),        
          175 => array ( 'name' => 'Pitcairn', 'iso' => 'PCN', 'region' => 'Oceania', 'isd_code' => '+872', 'currency' => 'NZD', 'symbol' => '$', 'dollar_value' => 1),        
          176 => array ( 'name' => 'Poland', 'iso' => 'POL', 'region' => 'Europe', 'isd_code' => '+48', 'currency' => 'PLN', 'symbol' => '$', 'dollar_value' => 1),        
          177 => array ( 'name' => 'Portugal', 'iso' => 'PRT', 'region' => 'Europe', 'isd_code' => '+351', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          178 => array ( 'name' => 'Puerto Rico', 'iso' => 'PRI', 'region' => 'Americas', 'isd_code' => '+1 787', 'currency' => 'USD', 'symbol' => '$', 'dollar_value' => 1),        
          179 => array ( 'name' => 'Qatar', 'iso' => 'QAT', 'region' => 'Asia', 'isd_code' => '+974', 'currency' => 'QAR', 'symbol' => '$', 'dollar_value' => 1),        
          180 => array ( 'name' => 'Réunion', 'iso' => 'REU', 'region' => 'Africa', 'isd_code' => '+262', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          181 => array ( 'name' => 'Romania', 'iso' => 'ROU', 'region' => 'Europe', 'isd_code' => '+40', 'currency' => 'RON', 'symbol' => '$', 'dollar_value' => 1),        
          182 => array ( 'name' => 'Russian Federation', 'iso' => 'RUS', 'region' => 'Europe', 'isd_code' => '+7', 'currency' => 'RUB', 'symbol' => '$', 'dollar_value' => 1),        
          183 => array ( 'name' => 'Rwanda', 'iso' => 'RWA', 'region' => 'Africa', 'isd_code' => '+250', 'currency' => 'RWF', 'symbol' => '$', 'dollar_value' => 1),        
          184 => array ( 'name' => 'Saint Barthélemy', 'iso' => 'BLM', 'region' => 'Americas', 'isd_code' => '+590', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          185 => array ( 'name' => 'Saint Helena, Ascension and Tristan da Cunha', 'iso' => 'SHN', 'region' => 'Africa', 'isd_code' => '+290', 'currency' => 'SHP', 'symbol' => '$', 'dollar_value' => 1),        
          186 => array ( 'name' => 'Saint Kitts and Nevis', 'iso' => 'KNA', 'region' => 'Americas', 'isd_code' => '+1 869', 'currency' => 'XCD', 'symbol' => '$', 'dollar_value' => 1),        
          187 => array ( 'name' => 'Saint Lucia', 'iso' => 'LCA', 'region' => 'Americas', 'isd_code' => '+1 758', 'currency' => 'XCD', 'symbol' => '$', 'dollar_value' => 1),        
          188 => array ( 'name' => 'Saint Martin (French part)', 'iso' => 'MAF', 'region' => 'Americas', 'isd_code' => '+590', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          189 => array ( 'name' => 'Saint Pierre and Miquelon', 'iso' => 'SPM', 'region' => 'Americas', 'isd_code' => '+508', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          190 => array ( 'name' => 'Saint Vincent and the Grenadines', 'iso' => 'VCT', 'region' => 'Americas', 'isd_code' => '+1 784', 'currency' => 'XCD', 'symbol' => '$', 'dollar_value' => 1),        
          191 => array ( 'name' => 'Samoa', 'iso' => 'WSM', 'region' => 'Oceania', 'isd_code' => '+685', 'currency' => 'WST', 'symbol' => '$', 'dollar_value' => 1),        
          192 => array ( 'name' => 'San Marino', 'iso' => 'SMR', 'region' => 'Europe', 'isd_code' => '+378', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          193 => array ( 'name' => 'Sao Tome and Principe', 'iso' => 'STP', 'region' => 'Africa', 'isd_code' => '+239', 'currency' => 'STD', 'symbol' => '$', 'dollar_value' => 1),        
          194 => array ( 'name' => 'Saudi Arabia', 'iso' => 'SAU', 'region' => 'Asia', 'isd_code' => '+966', 'currency' => 'SAR', 'symbol' => '$', 'dollar_value' => 1),        
          195 => array ( 'name' => 'Senegal', 'iso' => 'SEN', 'region' => 'Africa', 'isd_code' => '+221', 'currency' => 'XOF', 'symbol' => '$', 'dollar_value' => 1),        
          196 => array ( 'name' => 'Serbia', 'iso' => 'SRB', 'region' => 'Europe', 'isd_code' => '+381', 'currency' => 'RSD', 'symbol' => '$', 'dollar_value' => 1),        
          197 => array ( 'name' => 'Seychelles', 'iso' => 'SYC', 'region' => 'Africa', 'isd_code' => '+248', 'currency' => 'SCR', 'symbol' => '$', 'dollar_value' => 1),        
          198 => array ( 'name' => 'Sierra Leone', 'iso' => 'SLE', 'region' => 'Africa', 'isd_code' => '+232', 'currency' => 'SLL', 'symbol' => '$', 'dollar_value' => 1),        
          199 => array ( 'name' => 'Singapore', 'iso' => 'SGP', 'region' => 'Asia', 'isd_code' => '+65', 'currency' => 'SGD', 'symbol' => '$', 'dollar_value' => 1),        
          200 => array ( 'name' => 'Sint Maarten (Dutch part)', 'iso' => 'SXM', 'region' => 'Americas', 'isd_code' => '+1 721', 'currency' => 'ANG', 'symbol' => 'NAƒ', 'dollar_value' => 1),        
          201 => array ( 'name' => 'Slovakia', 'iso' => 'SVK', 'region' => 'Europe', 'isd_code' => '+421', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          202 => array ( 'name' => 'Slovenia', 'iso' => 'SVN', 'region' => 'Europe', 'isd_code' => '+386', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          203 => array ( 'name' => 'Solomon Islands', 'iso' => 'SLB', 'region' => 'Oceania', 'isd_code' => '+677', 'currency' => 'SBD', 'symbol' => '$', 'dollar_value' => 1),        
          204 => array ( 'name' => 'Somalia', 'iso' => 'SOM', 'region' => 'Africa', 'isd_code' => '+252', 'currency' => 'SOS', 'symbol' => '$', 'dollar_value' => 1),        
          205 => array ( 'name' => 'South Africa', 'iso' => 'ZAF', 'region' => 'Africa', 'isd_code' => '+27', 'currency' => 'ZAR', 'symbol' => '$', 'dollar_value' => 1),        
          206 => array ( 'name' => 'South Georgia and the South Sandwich Islands', 'iso' => 'SGS', 'region' => NULL, 'currency' => 'GBP', 'symbol' => '£', 'dollar_value' => 1, 'isd_code' => ''),        
          207 => array ( 'name' => 'South Sudan', 'iso' => 'SSD', 'region' => 'Africa', 'isd_code' => '+211', 'currency' => 'SSP', 'symbol' => '$', 'dollar_value' => 1),        
          208 => array ( 'name' => 'Spain', 'iso' => 'ESP', 'region' => 'Europe', 'isd_code' => '+34', 'currency' => 'EUR', 'symbol' => '€', 'dollar_value' => 1),        
          209 => array ( 'name' => 'Sri Lanka', 'iso' => 'LKA', 'region' => 'Asia', 'isd_code' => '+94', 'currency' => 'LKR', 'symbol' => '$', 'dollar_value' => 1),        
          210 => array ( 'name' => 'Sudan', 'iso' => 'SDN', 'region' => 'Africa', 'isd_code' => '+249', 'currency' => 'SDG', 'symbol' => '$', 'dollar_value' => 1),        
          211 => array ( 'name' => 'Suriname', 'iso' => 'SUR', 'region' => 'Americas', 'isd_code' => '+597', 'currency' => 'SRD', 'symbol' => '$', 'dollar_value' => 1),        
          212 => array ( 'name' => 'Svalbard and Jan Mayen', 'iso' => 'SJM', 'region' => 'Europe', 'isd_code' => '+47', 'currency' => 'NOK', 'symbol' => '$', 'dollar_value' => 1),        
          213 => array ( 'name' => 'Swaziland', 'iso' => 'SWZ', 'region' => 'Africa', 'isd_code' => '+268', 'currency' => 'SZL', 'symbol' => '$', 'dollar_value' => 1),        
          214 => array ( 'name' => 'Sweden', 'iso' => 'SWE', 'region' => 'Europe', 'isd_code' => '+46', 'currency' => 'SEK', 'symbol' => '$', 'dollar_value' => 1),        
          215 => array ( 'name' => 'Switzerland', 'iso' => 'CHE', 'region' => 'Europe', 'isd_code' => '+41', 'currency' => 'CHF', 'symbol' => '$', 'dollar_value' => 1),        
          216 => array ( 'name' => 'Syrian Arab Republic', 'iso' => 'SYR', 'region' => 'Asia', 'isd_code' => '+963', 'currency' => 'SYP', 'symbol' => '$', 'dollar_value' => 1),        
          217 => array ( 'name' => 'Taiwan, Province of China', 'iso' => 'TWN', 'region' => 'Asia', 'isd_code' => '+886', 'currency' => 'TWD', 'symbol' => '$', 'dollar_value' => 1),        
          218 => array ( 'name' => 'Tajikistan', 'iso' => 'TJK', 'region' => 'Asia', 'isd_code' => '+992', 'currency' => 'TJS', 'symbol' => '$', 'dollar_value' => 1),        
          219 => array ( 'name' => 'Tanzania, United Republic of', 'iso' => 'TZA', 'region' => 'Africa', 'isd_code' => '+255', 'currency' => 'TZS', 'symbol' => '$', 'dollar_value' => 1),        
          220 => array ( 'name' => 'Thailand', 'iso' => 'THA', 'region' => 'Asia', 'isd_code' => '+66', 'currency' => 'THB', 'symbol' => '$', 'dollar_value' => 1),        
          221 => array ( 'name' => 'Timor-Leste', 'iso' => 'TLS', 'region' => 'Asia', 'isd_code' => '+670', 'currency' => 'USD', 'symbol' => '$', 'dollar_value' => 1),        
          222 => array ( 'name' => 'Togo', 'iso' => 'TGO', 'region' => 'Africa', 'isd_code' => '+228', 'currency' => 'XOF', 'symbol' => '$', 'dollar_value' => 1),        
          223 => array ( 'name' => 'Tokelau', 'iso' => 'TKL', 'region' => 'Oceania', 'isd_code' => '+690', 'currency' => 'NZD', 'symbol' => '$', 'dollar_value' => 1),        
          224 => array ( 'name' => 'Tonga', 'iso' => 'TON', 'region' => 'Oceania', 'isd_code' => '+676', 'currency' => 'TOP', 'symbol' => '$', 'dollar_value' => 1),        
          225 => array ( 'name' => 'Trinidad and Tobago', 'iso' => 'TTO', 'region' => 'Americas', 'isd_code' => '+1 868', 'currency' => 'TTD', 'symbol' => '$', 'dollar_value' => 1),        
          226 => array ( 'name' => 'Tunisia', 'iso' => 'TUN', 'region' => 'Africa', 'isd_code' => '+216', 'currency' => 'TND', 'symbol' => '$', 'dollar_value' => 1),        
          227 => array ( 'name' => 'Turkey', 'iso' => 'TUR', 'region' => 'Asia', 'isd_code' => '+90', 'currency' => 'TRY', 'symbol' => '$', 'dollar_value' => 1),        
          228 => array ( 'name' => 'Turkmenistan', 'iso' => 'TKM', 'region' => 'Asia', 'isd_code' => '+993', 'currency' => 'TMT', 'symbol' => '$', 'dollar_value' => 1),        
          229 => array ( 'name' => 'Turks and Caicos Islands', 'iso' => 'TCA', 'region' => 'Americas', 'isd_code' => '+1 649', 'currency' => 'USD', 'symbol' => '$', 'dollar_value' => 1),        
          230 => array ( 'name' => 'Tuvalu', 'iso' => 'TUV', 'region' => 'Oceania', 'isd_code' => '+688', 'currency' => 'AUD', 'symbol' => 'AU$', 'dollar_value' => 1),        
          231 => array ( 'name' => 'Uganda', 'iso' => 'UGA', 'region' => 'Africa', 'isd_code' => '+256', 'currency' => 'UGX', 'symbol' => '$', 'dollar_value' => 1),        
          232 => array ( 'name' => 'Ukraine', 'iso' => 'UKR', 'region' => 'Europe', 'isd_code' => '+380', 'currency' => 'UAH', 'symbol' => '$', 'dollar_value' => 1),        
          233 => array ( 'name' => 'United Arab Emirates', 'iso' => 'ARE', 'region' => 'Asia', 'isd_code' => '+971', 'currency' => 'AED', 'symbol' => 'Dhs', 'dollar_value' => 1),        
          234 => array ( 'name' => 'United Kingdom of Great Britain and Northern Ireland', 'iso' => 'GBR', 'region' => 'Europe', 'isd_code' => '+44', 'currency' => 'GBP', 'symbol' => '£', 'dollar_value' => 1),        
          235 => array ( 'name' => 'United States of America', 'iso' => 'USA', 'region' => 'Americas', 'isd_code' => '+1', 'currency' => 'USD', 'symbol' => '$', 'dollar_value' => 1),        
          236 => array ( 'name' => 'United States Minor Outlying Islands', 'iso' => 'UMI', 'region' => NULL, 'isd_code' => '+1', 'currency' => 'USD', 'symbol' => '$', 'dollar_value' => 1),        
          237 => array ( 'name' => 'Uruguay', 'iso' => 'URY', 'region' => 'Americas', 'isd_code' => '+598', 'currency' => 'UYU', 'symbol' => '$', 'dollar_value' => 1),        
          238 => array ( 'name' => 'Uzbekistan', 'iso' => 'UZB', 'region' => 'Asia', 'isd_code' => '+998', 'currency' => 'UZS', 'symbol' => '$', 'dollar_value' => 1),        
          239 => array ( 'name' => 'Vanuatu', 'iso' => 'VUT', 'region' => 'Oceania', 'isd_code' => '+678', 'currency' => 'VUV', 'symbol' => '$', 'dollar_value' => 1),        
          240 => array ( 'name' => 'Venezuela (Bolivarian Republic of)', 'iso' => 'VEN', 'region' => 'Americas', 'isd_code' => '+58', 'currency' => 'VEF', 'symbol' => '$', 'dollar_value' => 1),        
          241 => array ( 'name' => 'Viet Nam', 'iso' => 'VNM', 'region' => 'Asia', 'isd_code' => '+84', 'currency' => 'VND', 'symbol' => '$', 'dollar_value' => 1),        
          242 => array ( 'name' => 'Virgin Islands (British)', 'iso' => 'VGB', 'region' => 'Americas', 'isd_code' => '+1 284', 'currency' => 'USD', 'symbol' => '$', 'dollar_value' => 1),        
          243 => array ( 'name' => 'Virgin Islands (U.S.)', 'iso' => 'VIR', 'region' => 'Americas', 'isd_code' => '+1 340', 'currency' => 'USD', 'symbol' => '$', 'dollar_value' => 1),        
          244 => array ( 'name' => 'Wallis and Futuna', 'iso' => 'WLF', 'region' => 'Oceania', 'isd_code' => '+681', 'currency' => 'XPF', 'symbol' => '$', 'dollar_value' => 1),        
          245 => array ( 'name' => 'Western Sahara', 'iso' => 'ESH', 'region' => 'Africa', 'isd_code' => '+212', 'currency' => 'MAD', 'symbol' => '$', 'dollar_value' => 1),        
          246 => array ( 'name' => 'Yemen', 'iso' => 'YEM', 'region' => 'Asia', 'isd_code' => '+967', 'currency' => 'YER', 'symbol' => '$', 'dollar_value' => 1),        
          247 => array ( 'name' => 'Zambia', 'iso' => 'ZMB', 'region' => 'Africa', 'isd_code' => '+260', 'currency' => 'ZMW', 'symbol' => '$', 'dollar_value' => 1),        
          248 => array ( 'name' => 'Zimbabwe', 'iso' => 'ZWE', 'region' => 'Africa', 'isd_code' => '+263', 'currency' => 'USD', 'symbol' => '$', 'dollar_value' => 1),        
          ));
   
        // $this->call(UsersTableSeeder::class);
    }
}
